# Generated by Django 5.0.6 on 2024-06-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_position', models.IntegerField()),
                ('figure_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('custom_rules', models.TextField()),
            ],
        ),
    ]
